package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name="alerta"
    ,schema="public"
)
public class Alerta  implements java.io.Serializable {


     private int idAlerta;
     private String fechaInicio;
     private String fechaLimite;
     private String estado;
     private Integer cantidadDias;
     private Integer cantidadEnfermos;
     private Integer idEnfermedades;

    public Alerta() {
    }

	
    public Alerta(int idAlerta) {
        this.idAlerta = idAlerta;
    }
    public Alerta(int idAlerta, String fechaInicio, String fechaLimite, String estado, Integer cantidadDias, Integer cantidadEnfermos, Integer idEnfermedades) {
       this.idAlerta = idAlerta;
       this.fechaInicio = fechaInicio;
       this.fechaLimite = fechaLimite;
       this.estado = estado;
       this.cantidadDias = cantidadDias;
       this.cantidadEnfermos = cantidadEnfermos;
       this.idEnfermedades = idEnfermedades;
    }
   
     @Id 

    
    @Column(name="id_alerta", unique=true, nullable=false)
    public int getIdAlerta() {
        return this.idAlerta;
    }
    
    public void setIdAlerta(int idAlerta) {
        this.idAlerta = idAlerta;
    }

    
    @Column(name="fecha_inicio")
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    
    @Column(name="fecha_limite")
    public String getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(String fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    
    @Column(name="estado", length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cantidad_dias")
    public Integer getCantidadDias() {
        return this.cantidadDias;
    }
    
    public void setCantidadDias(Integer cantidadDias) {
        this.cantidadDias = cantidadDias;
    }

    
    @Column(name="cantidad_enfermos")
    public Integer getCantidadEnfermos() {
        return this.cantidadEnfermos;
    }
    
    public void setCantidadEnfermos(Integer cantidadEnfermos) {
        this.cantidadEnfermos = cantidadEnfermos;
    }

    
    @Column(name="id_enfermedades")
    public Integer getIdEnfermedades() {
        return this.idEnfermedades;
    }
    
    public void setIdEnfermedades(Integer idEnfermedades) {
        this.idEnfermedades = idEnfermedades;
    }




}


