package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AsignacionRecorrido generated by hbm2java
 */
@Entity
@Table(name="asignacion_recorrido"
    ,schema="public"
)
public class AsignacionRecorrido  implements java.io.Serializable {


     private int idAsignacion;
     private String puntoA;
     private String puntoB;
     private String puntoC;
     private String puntoD;
     private String fecha;
     private String latitud;
     private String longitud;
     private Integer idGrupoAps;

    public AsignacionRecorrido() {
    }

	
    public AsignacionRecorrido(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public AsignacionRecorrido(int idAsignacion, String puntoA, String puntoB, String puntoC, String puntoD, String fecha, String latitud, String longitud, Integer idGrupoAps) {
       this.idAsignacion = idAsignacion;
       this.puntoA = puntoA;
       this.puntoB = puntoB;
       this.puntoC = puntoC;
       this.puntoD = puntoD;
       this.fecha = fecha;
       this.latitud = latitud;
       this.longitud = longitud;
       this.idGrupoAps = idGrupoAps;
    }
   
     @Id 

    
    @Column(name="id_asignacion", unique=true, nullable=false)
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    
    @Column(name="puntoA", length=100)
    public String getPuntoA() {
        return this.puntoA;
    }
    
    public void setPuntoA(String puntoA) {
        this.puntoA = puntoA;
    }

    
    @Column(name="puntoB", length=100)
    public String getPuntoB() {
        return this.puntoB;
    }
    
    public void setPuntoB(String puntoB) {
        this.puntoB = puntoB;
    }

    
    @Column(name="puntoC", length=100)
    public String getPuntoC() {
        return this.puntoC;
    }
    
    public void setPuntoC(String puntoC) {
        this.puntoC = puntoC;
    }

    
    @Column(name="puntoD", length=100)
    public String getPuntoD() {
        return this.puntoD;
    }
    
    public void setPuntoD(String puntoD) {
        this.puntoD = puntoD;
    }

    
    @Column(name="fecha")
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="latitud", length=25)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", length=25)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="id_grupo_aps")
    public Integer getIdGrupoAps() {
        return this.idGrupoAps;
    }
    
    public void setIdGrupoAps(Integer idGrupoAps) {
        this.idGrupoAps = idGrupoAps;
    }




}


