package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Barrio generated by hbm2java
 */
@Entity
@Table(name="barrio"
    ,schema="public"
)
public class Barrio  implements java.io.Serializable {


     private int idBarrio;
     private String barrio;
     private Integer idCiudad;

    public Barrio() {
    }

	
    public Barrio(int idBarrio) {
        this.idBarrio = idBarrio;
    }
    public Barrio(int idBarrio, String barrio, Integer idCiudad) {
       this.idBarrio = idBarrio;
       this.barrio = barrio;
       this.idCiudad = idCiudad;
    }
   
     @Id 

    
    @Column(name="id_barrio", unique=true, nullable=false)
    public int getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(int idBarrio) {
        this.idBarrio = idBarrio;
    }

    
    @Column(name="barrio", length=30)
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }

    
    @Column(name="id_ciudad")
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }




}


