package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CabInternacion generated by hbm2java
 */
@Entity
@Table(name="cab_internacion"
    ,schema="public"
)
public class CabInternacion  implements java.io.Serializable {


     private int idInternacion;
     private String horaInternacion;
     private String fechaInternacion;
     private String horaAlta;
     private String fechaAlta;
     private String observacionInternacion;
     private String estado;
     private Integer idPaciente;
     private Integer idPersonal;
     private Integer idEnfermedades;

    public CabInternacion() {
    }

	
    public CabInternacion(int idInternacion, String estado) {
        this.idInternacion = idInternacion;
        this.estado = estado;
    }
    public CabInternacion(int idInternacion, String horaInternacion, String fechaInternacion, String horaAlta, String fechaAlta, String observacionInternacion, String estado, Integer idPaciente, Integer idPersonal, Integer idEnfermedades) {
       this.idInternacion = idInternacion;
       this.horaInternacion = horaInternacion;
       this.fechaInternacion = fechaInternacion;
       this.horaAlta = horaAlta;
       this.fechaAlta = fechaAlta;
       this.observacionInternacion = observacionInternacion;
       this.estado = estado;
       this.idPaciente = idPaciente;
       this.idPersonal = idPersonal;
       this.idEnfermedades = idEnfermedades;
    }
   
     @Id 

    
    @Column(name="id_internacion", unique=true, nullable=false)
    public int getIdInternacion() {
        return this.idInternacion;
    }
    
    public void setIdInternacion(int idInternacion) {
        this.idInternacion = idInternacion;
    }

    
    @Column(name="hora_internacion", length=10)
    public String getHoraInternacion() {
        return this.horaInternacion;
    }
    
    public void setHoraInternacion(String horaInternacion) {
        this.horaInternacion = horaInternacion;
    }

    
    @Column(name="fecha_internacion", length=10)
    public String getFechaInternacion() {
        return this.fechaInternacion;
    }
    
    public void setFechaInternacion(String fechaInternacion) {
        this.fechaInternacion = fechaInternacion;
    }

    
    @Column(name="hora_alta", length=10)
    public String getHoraAlta() {
        return this.horaAlta;
    }
    
    public void setHoraAlta(String horaAlta) {
        this.horaAlta = horaAlta;
    }

    
    @Column(name="fecha_alta", length=10)
    public String getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(String fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    
    @Column(name="observacion_internacion", length=225)
    public String getObservacionInternacion() {
        return this.observacionInternacion;
    }
    
    public void setObservacionInternacion(String observacionInternacion) {
        this.observacionInternacion = observacionInternacion;
    }

    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="id_personal")
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }

    
    @Column(name="id_enfermedades")
    public Integer getIdEnfermedades() {
        return this.idEnfermedades;
    }
    
    public void setIdEnfermedades(Integer idEnfermedades) {
        this.idEnfermedades = idEnfermedades;
    }




}


