package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CabOrdenAnalisis generated by hbm2java
 */
@Entity
@Table(name="cab_orden_analisis"
    ,schema="public"
)
public class CabOrdenAnalisis  implements java.io.Serializable {


     private int idCabOrdenAnalisis;
     private Date fechaRegistroanalisis;
     private Date horaRegistroanalisis;
     private String estadoRegistroanalisis;
     private String documentoPaciente;
     private Integer idLaboratorio;
     private Integer idRegistroconsulta;

    public CabOrdenAnalisis() {
    }

	
    public CabOrdenAnalisis(int idCabOrdenAnalisis) {
        this.idCabOrdenAnalisis = idCabOrdenAnalisis;
    }
    public CabOrdenAnalisis(int idCabOrdenAnalisis, Date fechaRegistroanalisis, Date horaRegistroanalisis, String estadoRegistroanalisis, String documentoPaciente, Integer idLaboratorio, Integer idRegistroconsulta) {
       this.idCabOrdenAnalisis = idCabOrdenAnalisis;
       this.fechaRegistroanalisis = fechaRegistroanalisis;
       this.horaRegistroanalisis = horaRegistroanalisis;
       this.estadoRegistroanalisis = estadoRegistroanalisis;
       this.documentoPaciente = documentoPaciente;
       this.idLaboratorio = idLaboratorio;
       this.idRegistroconsulta = idRegistroconsulta;
    }
   
     @Id 

    
    @Column(name="id_cab_orden_analisis", unique=true, nullable=false)
    public int getIdCabOrdenAnalisis() {
        return this.idCabOrdenAnalisis;
    }
    
    public void setIdCabOrdenAnalisis(int idCabOrdenAnalisis) {
        this.idCabOrdenAnalisis = idCabOrdenAnalisis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_registroanalisis", length=13)
    public Date getFechaRegistroanalisis() {
        return this.fechaRegistroanalisis;
    }
    
    public void setFechaRegistroanalisis(Date fechaRegistroanalisis) {
        this.fechaRegistroanalisis = fechaRegistroanalisis;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_registroanalisis", length=15)
    public Date getHoraRegistroanalisis() {
        return this.horaRegistroanalisis;
    }
    
    public void setHoraRegistroanalisis(Date horaRegistroanalisis) {
        this.horaRegistroanalisis = horaRegistroanalisis;
    }

    
    @Column(name="estado_registroanalisis")
    public String getEstadoRegistroanalisis() {
        return this.estadoRegistroanalisis;
    }
    
    public void setEstadoRegistroanalisis(String estadoRegistroanalisis) {
        this.estadoRegistroanalisis = estadoRegistroanalisis;
    }

    
    @Column(name="documento_paciente")
    public String getDocumentoPaciente() {
        return this.documentoPaciente;
    }
    
    public void setDocumentoPaciente(String documentoPaciente) {
        this.documentoPaciente = documentoPaciente;
    }

    
    @Column(name="id_laboratorio")
    public Integer getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(Integer idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }

    
    @Column(name="id_registroconsulta")
    public Integer getIdRegistroconsulta() {
        return this.idRegistroconsulta;
    }
    
    public void setIdRegistroconsulta(Integer idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }




}


