package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CabResultadoAnalisis generated by hbm2java
 */
@Entity
@Table(name="cab_resultado_analisis"
    ,schema="public"
)
public class CabResultadoAnalisis  implements java.io.Serializable {


     private int idCabResultado;
     private Date fecha;
     private Date hora;
     private Integer idCabOrdenAnalisis;
     private Integer idPaciente;

    public CabResultadoAnalisis() {
    }

	
    public CabResultadoAnalisis(int idCabResultado) {
        this.idCabResultado = idCabResultado;
    }
    public CabResultadoAnalisis(int idCabResultado, Date fecha, Date hora, Integer idCabOrdenAnalisis, Integer idPaciente) {
       this.idCabResultado = idCabResultado;
       this.fecha = fecha;
       this.hora = hora;
       this.idCabOrdenAnalisis = idCabOrdenAnalisis;
       this.idPaciente = idPaciente;
    }
   
     @Id 

    
    @Column(name="id_cab_resultado", unique=true, nullable=false)
    public int getIdCabResultado() {
        return this.idCabResultado;
    }
    
    public void setIdCabResultado(int idCabResultado) {
        this.idCabResultado = idCabResultado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora", length=15)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    
    @Column(name="id_cab_orden_analisis")
    public Integer getIdCabOrdenAnalisis() {
        return this.idCabOrdenAnalisis;
    }
    
    public void setIdCabOrdenAnalisis(Integer idCabOrdenAnalisis) {
        this.idCabOrdenAnalisis = idCabOrdenAnalisis;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }




}


