package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CentroDeSalud generated by hbm2java
 */
@Entity
@Table(name="centro_de_salud"
    ,schema="public"
)
public class CentroDeSalud  implements java.io.Serializable {


     private int idCentro;
     private String nombreCentro;
     private String emailCentro;
     private String telefonoCentro;
     private String direccionCentro;

    public CentroDeSalud() {
    }

	
    public CentroDeSalud(int idCentro, String nombreCentro, String direccionCentro) {
        this.idCentro = idCentro;
        this.nombreCentro = nombreCentro;
        this.direccionCentro = direccionCentro;
    }
    public CentroDeSalud(int idCentro, String nombreCentro, String emailCentro, String telefonoCentro, String direccionCentro) {
       this.idCentro = idCentro;
       this.nombreCentro = nombreCentro;
       this.emailCentro = emailCentro;
       this.telefonoCentro = telefonoCentro;
       this.direccionCentro = direccionCentro;
    }
   
     @Id 

    
    @Column(name="id_centro", unique=true, nullable=false)
    public int getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(int idCentro) {
        this.idCentro = idCentro;
    }

    
    @Column(name="nombre_centro", nullable=false, length=25)
    public String getNombreCentro() {
        return this.nombreCentro;
    }
    
    public void setNombreCentro(String nombreCentro) {
        this.nombreCentro = nombreCentro;
    }

    
    @Column(name="email_centro", length=30)
    public String getEmailCentro() {
        return this.emailCentro;
    }
    
    public void setEmailCentro(String emailCentro) {
        this.emailCentro = emailCentro;
    }

    
    @Column(name="telefono_centro", length=30)
    public String getTelefonoCentro() {
        return this.telefonoCentro;
    }
    
    public void setTelefonoCentro(String telefonoCentro) {
        this.telefonoCentro = telefonoCentro;
    }

    
    @Column(name="direccion_centro", nullable=false, length=30)
    public String getDireccionCentro() {
        return this.direccionCentro;
    }
    
    public void setDireccionCentro(String direccionCentro) {
        this.direccionCentro = direccionCentro;
    }




}


