package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="ciudad"
    ,schema="public"
)
public class Ciudad  implements java.io.Serializable {


     private int idCiudad;
     private String nombreCiudad;
     private Integer idDepartamento;

    public Ciudad() {
    }

	
    public Ciudad(int idCiudad, String nombreCiudad) {
        this.idCiudad = idCiudad;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(int idCiudad, String nombreCiudad, Integer idDepartamento) {
       this.idCiudad = idCiudad;
       this.nombreCiudad = nombreCiudad;
       this.idDepartamento = idDepartamento;
    }
   
     @Id 

    
    @Column(name="id_ciudad", unique=true, nullable=false)
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }

    
    @Column(name="nombre_ciudad", nullable=false, length=30)
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }

    
    @Column(name="id_departamento")
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }




}


