package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Consultorio generated by hbm2java
 */
@Entity
@Table(name="consultorio"
    ,schema="public"
)
public class Consultorio  implements java.io.Serializable {


     private int idConsultorio;
     private Integer numeroConsultorio;

    public Consultorio() {
    }

	
    public Consultorio(int idConsultorio) {
        this.idConsultorio = idConsultorio;
    }
    public Consultorio(int idConsultorio, Integer numeroConsultorio) {
       this.idConsultorio = idConsultorio;
       this.numeroConsultorio = numeroConsultorio;
    }
   
     @Id 

    
    @Column(name="id_consultorio", unique=true, nullable=false)
    public int getIdConsultorio() {
        return this.idConsultorio;
    }
    
    public void setIdConsultorio(int idConsultorio) {
        this.idConsultorio = idConsultorio;
    }

    
    @Column(name="numero_consultorio")
    public Integer getNumeroConsultorio() {
        return this.numeroConsultorio;
    }
    
    public void setNumeroConsultorio(Integer numeroConsultorio) {
        this.numeroConsultorio = numeroConsultorio;
    }




}


