package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name="contacto"
    ,schema="public"
)
public class Contacto  implements java.io.Serializable {


     private int idContacto;
     private String nombresContacto;
     private String apellidosContacto;
     private String documentoContacto;
     private String nacimientoContacto;
     private Integer edadContacto;
     private String direccion;
     private String telefonoContacto;
     private String parentesco;
     private String emailContacto;
     private Integer idPaciente;
     private Integer idSexo;

    public Contacto() {
    }

	
    public Contacto(int idContacto, String nombresContacto, String nacimientoContacto) {
        this.idContacto = idContacto;
        this.nombresContacto = nombresContacto;
        this.nacimientoContacto = nacimientoContacto;
    }
    public Contacto(int idContacto, String nombresContacto, String apellidosContacto, String documentoContacto, String nacimientoContacto, Integer edadContacto, String direccion, String telefonoContacto, String parentesco, String emailContacto, Integer idPaciente, Integer idSexo) {
       this.idContacto = idContacto;
       this.nombresContacto = nombresContacto;
       this.apellidosContacto = apellidosContacto;
       this.documentoContacto = documentoContacto;
       this.nacimientoContacto = nacimientoContacto;
       this.edadContacto = edadContacto;
       this.direccion = direccion;
       this.telefonoContacto = telefonoContacto;
       this.parentesco = parentesco;
       this.emailContacto = emailContacto;
       this.idPaciente = idPaciente;
       this.idSexo = idSexo;
    }
   
     @Id 

    
    @Column(name="id_contacto", unique=true, nullable=false)
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }

    
    @Column(name="nombres_contacto", nullable=false, length=40)
    public String getNombresContacto() {
        return this.nombresContacto;
    }
    
    public void setNombresContacto(String nombresContacto) {
        this.nombresContacto = nombresContacto;
    }

    
    @Column(name="apellidos_contacto")
    public String getApellidosContacto() {
        return this.apellidosContacto;
    }
    
    public void setApellidosContacto(String apellidosContacto) {
        this.apellidosContacto = apellidosContacto;
    }

    
    @Column(name="documento_contacto")
    public String getDocumentoContacto() {
        return this.documentoContacto;
    }
    
    public void setDocumentoContacto(String documentoContacto) {
        this.documentoContacto = documentoContacto;
    }

    
    @Column(name="nacimiento_contacto", nullable=false, length=25)
    public String getNacimientoContacto() {
        return this.nacimientoContacto;
    }
    
    public void setNacimientoContacto(String nacimientoContacto) {
        this.nacimientoContacto = nacimientoContacto;
    }

    
    @Column(name="edad_contacto")
    public Integer getEdadContacto() {
        return this.edadContacto;
    }
    
    public void setEdadContacto(Integer edadContacto) {
        this.edadContacto = edadContacto;
    }

    
    @Column(name="direccion", length=10)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono_contacto", length=25)
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }

    
    @Column(name="parentesco")
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }

    
    @Column(name="email_contacto", length=30)
    public String getEmailContacto() {
        return this.emailContacto;
    }
    
    public void setEmailContacto(String emailContacto) {
        this.emailContacto = emailContacto;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="id_sexo")
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }




}


