package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name="departamentos"
    ,schema="public"
)
public class Departamentos  implements java.io.Serializable {


     private int idDepartamento;
     private String nombreDepartamento;
     private Integer idPais;

    public Departamentos() {
    }

	
    public Departamentos(int idDepartamento, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamentos(int idDepartamento, String nombreDepartamento, Integer idPais) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.idPais = idPais;
    }
   
     @Id 

    
    @Column(name="id_departamento", unique=true, nullable=false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="nombre_departamento", nullable=false, length=30)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

    
    @Column(name="id_pais")
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }




}


