package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleOrdenAnalisis generated by hbm2java
 */
@Entity
@Table(name="detalle_orden_analisis"
    ,schema="public"
)
public class DetalleOrdenAnalisis  implements java.io.Serializable {


     private int idOrdenDetalleAnalisis;
     private String observaciones;
     private Integer idTipoanalisis;
     private Integer idCabOrdenAnalisis;

    public DetalleOrdenAnalisis() {
    }

	
    public DetalleOrdenAnalisis(int idOrdenDetalleAnalisis) {
        this.idOrdenDetalleAnalisis = idOrdenDetalleAnalisis;
    }
    public DetalleOrdenAnalisis(int idOrdenDetalleAnalisis, String observaciones, Integer idTipoanalisis, Integer idCabOrdenAnalisis) {
       this.idOrdenDetalleAnalisis = idOrdenDetalleAnalisis;
       this.observaciones = observaciones;
       this.idTipoanalisis = idTipoanalisis;
       this.idCabOrdenAnalisis = idCabOrdenAnalisis;
    }
   
     @Id 

    
    @Column(name="id_orden_detalle_analisis", unique=true, nullable=false)
    public int getIdOrdenDetalleAnalisis() {
        return this.idOrdenDetalleAnalisis;
    }
    
    public void setIdOrdenDetalleAnalisis(int idOrdenDetalleAnalisis) {
        this.idOrdenDetalleAnalisis = idOrdenDetalleAnalisis;
    }

    
    @Column(name="observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="id_tipoanalisis")
    public Integer getIdTipoanalisis() {
        return this.idTipoanalisis;
    }
    
    public void setIdTipoanalisis(Integer idTipoanalisis) {
        this.idTipoanalisis = idTipoanalisis;
    }

    
    @Column(name="id_cab_orden_analisis")
    public Integer getIdCabOrdenAnalisis() {
        return this.idCabOrdenAnalisis;
    }
    
    public void setIdCabOrdenAnalisis(Integer idCabOrdenAnalisis) {
        this.idCabOrdenAnalisis = idCabOrdenAnalisis;
    }




}


