package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleGrupoAps generated by hbm2java
 */
@Entity
@Table(name="detalle_grupo_aps"
    ,schema="public"
)
public class DetalleGrupoAps  implements java.io.Serializable {


     private int idDetallUnidadaps;
     private Integer idPersonal;
     private Integer idGrupoAps;

    public DetalleGrupoAps() {
    }

	
    public DetalleGrupoAps(int idDetallUnidadaps) {
        this.idDetallUnidadaps = idDetallUnidadaps;
    }
    public DetalleGrupoAps(int idDetallUnidadaps, Integer idPersonal, Integer idGrupoAps) {
       this.idDetallUnidadaps = idDetallUnidadaps;
       this.idPersonal = idPersonal;
       this.idGrupoAps = idGrupoAps;
    }
   
     @Id 

    
    @Column(name="id_detall_unidadaps", unique=true, nullable=false)
    public int getIdDetallUnidadaps() {
        return this.idDetallUnidadaps;
    }
    
    public void setIdDetallUnidadaps(int idDetallUnidadaps) {
        this.idDetallUnidadaps = idDetallUnidadaps;
    }

    
    @Column(name="id_personal")
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }

    
    @Column(name="id_grupo_aps")
    public Integer getIdGrupoAps() {
        return this.idGrupoAps;
    }
    
    public void setIdGrupoAps(Integer idGrupoAps) {
        this.idGrupoAps = idGrupoAps;
    }




}


