package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleCabResultadoAnalisis generated by hbm2java
 */
@Entity
@Table(name="detalle_cab_resultado_analisis"
    ,schema="public"
)
public class DetalleCabResultadoAnalisis  implements java.io.Serializable {


     private int idDetalleResultado;
     private String nombre;
     private String valor;
     private Integer idCabResultado;
     private Integer idTipoanalisis;

    public DetalleCabResultadoAnalisis() {
    }

	
    public DetalleCabResultadoAnalisis(int idDetalleResultado) {
        this.idDetalleResultado = idDetalleResultado;
    }
    public DetalleCabResultadoAnalisis(int idDetalleResultado, String nombre, String valor, Integer idCabResultado, Integer idTipoanalisis) {
       this.idDetalleResultado = idDetalleResultado;
       this.nombre = nombre;
       this.valor = valor;
       this.idCabResultado = idCabResultado;
       this.idTipoanalisis = idTipoanalisis;
    }
   
     @Id 

    
    @Column(name="id_detalle_resultado", unique=true, nullable=false)
    public int getIdDetalleResultado() {
        return this.idDetalleResultado;
    }
    
    public void setIdDetalleResultado(int idDetalleResultado) {
        this.idDetalleResultado = idDetalleResultado;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="valor")
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="id_cab_resultado")
    public Integer getIdCabResultado() {
        return this.idCabResultado;
    }
    
    public void setIdCabResultado(Integer idCabResultado) {
        this.idCabResultado = idCabResultado;
    }

    
    @Column(name="id_tipoanalisis")
    public Integer getIdTipoanalisis() {
        return this.idTipoanalisis;
    }
    
    public void setIdTipoanalisis(Integer idTipoanalisis) {
        this.idTipoanalisis = idTipoanalisis;
    }




}


