package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetallePromocion generated by hbm2java
 */
@Entity
@Table(name="detalle_promocion"
    ,schema="public"
)
public class DetallePromocion  implements java.io.Serializable {


     private int idDetallePromocion;
     private Integer idPromocion;
     private Integer idPersonal;

    public DetallePromocion() {
    }

	
    public DetallePromocion(int idDetallePromocion) {
        this.idDetallePromocion = idDetallePromocion;
    }
    public DetallePromocion(int idDetallePromocion, Integer idPromocion, Integer idPersonal) {
       this.idDetallePromocion = idDetallePromocion;
       this.idPromocion = idPromocion;
       this.idPersonal = idPersonal;
    }
   
     @Id 

    
    @Column(name="id_detalle_promocion", unique=true, nullable=false)
    public int getIdDetallePromocion() {
        return this.idDetallePromocion;
    }
    
    public void setIdDetallePromocion(int idDetallePromocion) {
        this.idDetallePromocion = idDetallePromocion;
    }

    
    @Column(name="id_promocion")
    public Integer getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(Integer idPromocion) {
        this.idPromocion = idPromocion;
    }

    
    @Column(name="id_personal")
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }




}


