package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleAsignacion generated by hbm2java
 */
@Entity
@Table(name="detalle_asignacion"
    ,schema="public"
)
public class DetalleAsignacion  implements java.io.Serializable {


     private int idDetalleAsignacion;
     private String observacion;
     private Integer idPaciente;
     private Integer idAsignacion;

    public DetalleAsignacion() {
    }

	
    public DetalleAsignacion(int idDetalleAsignacion) {
        this.idDetalleAsignacion = idDetalleAsignacion;
    }
    public DetalleAsignacion(int idDetalleAsignacion, String observacion, Integer idPaciente, Integer idAsignacion) {
       this.idDetalleAsignacion = idDetalleAsignacion;
       this.observacion = observacion;
       this.idPaciente = idPaciente;
       this.idAsignacion = idAsignacion;
    }
   
     @Id 

    
    @Column(name="id_detalle_asignacion", unique=true, nullable=false)
    public int getIdDetalleAsignacion() {
        return this.idDetalleAsignacion;
    }
    
    public void setIdDetalleAsignacion(int idDetalleAsignacion) {
        this.idDetalleAsignacion = idDetalleAsignacion;
    }

    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="id_asignacion")
    public Integer getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(Integer idAsignacion) {
        this.idAsignacion = idAsignacion;
    }




}


