package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleInternacion generated by hbm2java
 */
@Entity
@Table(name="detalle_internacion"
    ,schema="public"
)
public class DetalleInternacion  implements java.io.Serializable {


     private int idDetalleInternacion;
     private String observacion;
     private Integer cantidadRecursos;
     private Integer idInternacion;
     private Integer idRecursoInternacion;

    public DetalleInternacion() {
    }

	
    public DetalleInternacion(int idDetalleInternacion) {
        this.idDetalleInternacion = idDetalleInternacion;
    }
    public DetalleInternacion(int idDetalleInternacion, String observacion, Integer cantidadRecursos, Integer idInternacion, Integer idRecursoInternacion) {
       this.idDetalleInternacion = idDetalleInternacion;
       this.observacion = observacion;
       this.cantidadRecursos = cantidadRecursos;
       this.idInternacion = idInternacion;
       this.idRecursoInternacion = idRecursoInternacion;
    }
   
     @Id 

    
    @Column(name="id_detalle_internacion", unique=true, nullable=false)
    public int getIdDetalleInternacion() {
        return this.idDetalleInternacion;
    }
    
    public void setIdDetalleInternacion(int idDetalleInternacion) {
        this.idDetalleInternacion = idDetalleInternacion;
    }

    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="cantidad_recursos")
    public Integer getCantidadRecursos() {
        return this.cantidadRecursos;
    }
    
    public void setCantidadRecursos(Integer cantidadRecursos) {
        this.cantidadRecursos = cantidadRecursos;
    }

    
    @Column(name="id_internacion")
    public Integer getIdInternacion() {
        return this.idInternacion;
    }
    
    public void setIdInternacion(Integer idInternacion) {
        this.idInternacion = idInternacion;
    }

    
    @Column(name="id_recurso_internacion")
    public Integer getIdRecursoInternacion() {
        return this.idRecursoInternacion;
    }
    
    public void setIdRecursoInternacion(Integer idRecursoInternacion) {
        this.idRecursoInternacion = idRecursoInternacion;
    }




}


