package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Diagnostico generated by hbm2java
 */
@Entity
@Table(name="diagnostico"
    ,schema="public"
)
public class Diagnostico  implements java.io.Serializable {


     private int idDiagnostico;
     private String observacion;
     private Integer idRegistroconsulta;
     private Integer idEnfermedades;

    public Diagnostico() {
    }

	
    public Diagnostico(int idDiagnostico) {
        this.idDiagnostico = idDiagnostico;
    }
    public Diagnostico(int idDiagnostico, String observacion, Integer idRegistroconsulta, Integer idEnfermedades) {
       this.idDiagnostico = idDiagnostico;
       this.observacion = observacion;
       this.idRegistroconsulta = idRegistroconsulta;
       this.idEnfermedades = idEnfermedades;
    }
   
     @Id 

    
    @Column(name="id_diagnostico", unique=true, nullable=false)
    public int getIdDiagnostico() {
        return this.idDiagnostico;
    }
    
    public void setIdDiagnostico(int idDiagnostico) {
        this.idDiagnostico = idDiagnostico;
    }

    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="id_registroconsulta")
    public Integer getIdRegistroconsulta() {
        return this.idRegistroconsulta;
    }
    
    public void setIdRegistroconsulta(Integer idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }

    
    @Column(name="id_enfermedades")
    public Integer getIdEnfermedades() {
        return this.idEnfermedades;
    }
    
    public void setIdEnfermedades(Integer idEnfermedades) {
        this.idEnfermedades = idEnfermedades;
    }




}


