package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enfermedades generated by hbm2java
 */
@Entity
@Table(name="enfermedades"
    ,schema="public"
)
public class Enfermedades  implements java.io.Serializable {


     private int idEnfermedades;
     private String clase;

    public Enfermedades() {
    }

    public Enfermedades(int idEnfermedades, String clase) {
       this.idEnfermedades = idEnfermedades;
       this.clase = clase;
    }
   
     @Id 

    
    @Column(name="id_enfermedades", unique=true, nullable=false)
    public int getIdEnfermedades() {
        return this.idEnfermedades;
    }
    
    public void setIdEnfermedades(int idEnfermedades) {
        this.idEnfermedades = idEnfermedades;
    }

    
    @Column(name="clase", nullable=false)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }




}


