package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrupoAps generated by hbm2java
 */
@Entity
@Table(name="grupo_aps"
    ,schema="public"
)
public class GrupoAps  implements java.io.Serializable {


     private int idGrupoAps;
     private String codGrupo;
     private String observacionesGrupoaps;
     private Integer idCentro;

    public GrupoAps() {
    }

	
    public GrupoAps(int idGrupoAps) {
        this.idGrupoAps = idGrupoAps;
    }
    public GrupoAps(int idGrupoAps, String codGrupo, String observacionesGrupoaps, Integer idCentro) {
       this.idGrupoAps = idGrupoAps;
       this.codGrupo = codGrupo;
       this.observacionesGrupoaps = observacionesGrupoaps;
       this.idCentro = idCentro;
    }
   
     @Id 

    
    @Column(name="id_grupo_aps", unique=true, nullable=false)
    public int getIdGrupoAps() {
        return this.idGrupoAps;
    }
    
    public void setIdGrupoAps(int idGrupoAps) {
        this.idGrupoAps = idGrupoAps;
    }

    
    @Column(name="cod_grupo")
    public String getCodGrupo() {
        return this.codGrupo;
    }
    
    public void setCodGrupo(String codGrupo) {
        this.codGrupo = codGrupo;
    }

    
    @Column(name="observaciones_grupoaps")
    public String getObservacionesGrupoaps() {
        return this.observacionesGrupoaps;
    }
    
    public void setObservacionesGrupoaps(String observacionesGrupoaps) {
        this.observacionesGrupoaps = observacionesGrupoaps;
    }

    
    @Column(name="id_centro")
    public Integer getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(Integer idCentro) {
        this.idCentro = idCentro;
    }




}


