package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HistorialPaciente generated by hbm2java
 */
@Entity
@Table(name="historial_paciente"
    ,schema="public"
)
public class HistorialPaciente  implements java.io.Serializable {


     private int idHistorial;
     private String observacion;
     private Integer idRegistroconsulta;
     private Integer idInternacion;
     private Integer idPaciente;

    public HistorialPaciente() {
    }

	
    public HistorialPaciente(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public HistorialPaciente(int idHistorial, String observacion, Integer idRegistroconsulta, Integer idInternacion, Integer idPaciente) {
       this.idHistorial = idHistorial;
       this.observacion = observacion;
       this.idRegistroconsulta = idRegistroconsulta;
       this.idInternacion = idInternacion;
       this.idPaciente = idPaciente;
    }
   
     @Id 

    
    @Column(name="id_historial", unique=true, nullable=false)
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }

    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="id_registroconsulta")
    public Integer getIdRegistroconsulta() {
        return this.idRegistroconsulta;
    }
    
    public void setIdRegistroconsulta(Integer idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }

    
    @Column(name="id_internacion")
    public Integer getIdInternacion() {
        return this.idInternacion;
    }
    
    public void setIdInternacion(Integer idInternacion) {
        this.idInternacion = idInternacion;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }




}


