package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsumoAps generated by hbm2java
 */
@Entity
@Table(name="insumo_aps"
    ,schema="public"
)
public class InsumoAps  implements java.io.Serializable {


     private int idInsumoaps;
     private Integer cantidadInsumoaps;
     private Integer idGrupoAps;

    public InsumoAps() {
    }

	
    public InsumoAps(int idInsumoaps) {
        this.idInsumoaps = idInsumoaps;
    }
    public InsumoAps(int idInsumoaps, Integer cantidadInsumoaps, Integer idGrupoAps) {
       this.idInsumoaps = idInsumoaps;
       this.cantidadInsumoaps = cantidadInsumoaps;
       this.idGrupoAps = idGrupoAps;
    }
   
     @Id 

    
    @Column(name="id_insumoaps", unique=true, nullable=false)
    public int getIdInsumoaps() {
        return this.idInsumoaps;
    }
    
    public void setIdInsumoaps(int idInsumoaps) {
        this.idInsumoaps = idInsumoaps;
    }

    
    @Column(name="cantidad_insumoaps")
    public Integer getCantidadInsumoaps() {
        return this.cantidadInsumoaps;
    }
    
    public void setCantidadInsumoaps(Integer cantidadInsumoaps) {
        this.cantidadInsumoaps = cantidadInsumoaps;
    }

    
    @Column(name="id_grupo_aps")
    public Integer getIdGrupoAps() {
        return this.idGrupoAps;
    }
    
    public void setIdGrupoAps(Integer idGrupoAps) {
        this.idGrupoAps = idGrupoAps;
    }




}


