package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsumoFarmaceutico generated by hbm2java
 */
@Entity
@Table(name="insumo_farmaceutico"
    ,schema="public"
)
public class InsumoFarmaceutico  implements java.io.Serializable {


     private int idInsumo;
     private String nombreInsumo;
     private int cantidadInsumo;
     private int cantidadinsumoMin;
     private String vencimientoInsumo;
     private Integer idProveedor;

    public InsumoFarmaceutico() {
    }

	
    public InsumoFarmaceutico(int idInsumo, String nombreInsumo, int cantidadInsumo, int cantidadinsumoMin, String vencimientoInsumo) {
        this.idInsumo = idInsumo;
        this.nombreInsumo = nombreInsumo;
        this.cantidadInsumo = cantidadInsumo;
        this.cantidadinsumoMin = cantidadinsumoMin;
        this.vencimientoInsumo = vencimientoInsumo;
    }
    public InsumoFarmaceutico(int idInsumo, String nombreInsumo, int cantidadInsumo, int cantidadinsumoMin, String vencimientoInsumo, Integer idProveedor) {
       this.idInsumo = idInsumo;
       this.nombreInsumo = nombreInsumo;
       this.cantidadInsumo = cantidadInsumo;
       this.cantidadinsumoMin = cantidadinsumoMin;
       this.vencimientoInsumo = vencimientoInsumo;
       this.idProveedor = idProveedor;
    }
   
     @Id 

    
    @Column(name="id_insumo", unique=true, nullable=false)
    public int getIdInsumo() {
        return this.idInsumo;
    }
    
    public void setIdInsumo(int idInsumo) {
        this.idInsumo = idInsumo;
    }

    
    @Column(name="nombre_insumo", nullable=false, length=25)
    public String getNombreInsumo() {
        return this.nombreInsumo;
    }
    
    public void setNombreInsumo(String nombreInsumo) {
        this.nombreInsumo = nombreInsumo;
    }

    
    @Column(name="cantidad_insumo", nullable=false)
    public int getCantidadInsumo() {
        return this.cantidadInsumo;
    }
    
    public void setCantidadInsumo(int cantidadInsumo) {
        this.cantidadInsumo = cantidadInsumo;
    }

    
    @Column(name="cantidadinsumo_min", nullable=false)
    public int getCantidadinsumoMin() {
        return this.cantidadinsumoMin;
    }
    
    public void setCantidadinsumoMin(int cantidadinsumoMin) {
        this.cantidadinsumoMin = cantidadinsumoMin;
    }

    
    @Column(name="vencimiento_insumo", nullable=false, length=25)
    public String getVencimientoInsumo() {
        return this.vencimientoInsumo;
    }
    
    public void setVencimientoInsumo(String vencimientoInsumo) {
        this.vencimientoInsumo = vencimientoInsumo;
    }

    
    @Column(name="id_proveedor")
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }




}


