package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nacionalidad generated by hbm2java
 */
@Entity
@Table(name="nacionalidad"
    ,schema="public"
)
public class Nacionalidad  implements java.io.Serializable {


     private int idNacionalidad;
     private String nacionalidad;
     private String tipoDocumento;
     private Integer idPais;

    public Nacionalidad() {
    }

	
    public Nacionalidad(int idNacionalidad, String nacionalidad) {
        this.idNacionalidad = idNacionalidad;
        this.nacionalidad = nacionalidad;
    }
    public Nacionalidad(int idNacionalidad, String nacionalidad, String tipoDocumento, Integer idPais) {
       this.idNacionalidad = idNacionalidad;
       this.nacionalidad = nacionalidad;
       this.tipoDocumento = tipoDocumento;
       this.idPais = idPais;
    }
   
     @Id 

    
    @Column(name="id_nacionalidad", unique=true, nullable=false)
    public int getIdNacionalidad() {
        return this.idNacionalidad;
    }
    
    public void setIdNacionalidad(int idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }

    
    @Column(name="nacionalidad", nullable=false, length=25)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="tipo_documento")
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    
    @Column(name="id_pais")
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }




}


