package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,schema="public"
)
public class Paciente  implements java.io.Serializable {


     private int idPaciente;
     private String nombresPaciente;
     private String apellidosPaciente;
     private Integer documentoPaciente;
     private String nacimientoPaciente;
     private Integer edadPaciente;
     private String telefonoPaciente;
     private String emailPaciente;
     private String latitud;
     private String longitud;
     private Integer idBarrio;
     private Integer idSexo;
     private Integer idSangre;
     private Integer idNacionalidad;

    public Paciente() {
    }

	
    public Paciente(int idPaciente, String nombresPaciente, String nacimientoPaciente) {
        this.idPaciente = idPaciente;
        this.nombresPaciente = nombresPaciente;
        this.nacimientoPaciente = nacimientoPaciente;
    }
    public Paciente(int idPaciente, String nombresPaciente, String apellidosPaciente, Integer documentoPaciente, String nacimientoPaciente, Integer edadPaciente, String telefonoPaciente, String emailPaciente, String latitud, String longitud, Integer idBarrio, Integer idSexo, Integer idSangre, Integer idNacionalidad) {
       this.idPaciente = idPaciente;
       this.nombresPaciente = nombresPaciente;
       this.apellidosPaciente = apellidosPaciente;
       this.documentoPaciente = documentoPaciente;
       this.nacimientoPaciente = nacimientoPaciente;
       this.edadPaciente = edadPaciente;
       this.telefonoPaciente = telefonoPaciente;
       this.emailPaciente = emailPaciente;
       this.latitud = latitud;
       this.longitud = longitud;
       this.idBarrio = idBarrio;
       this.idSexo = idSexo;
       this.idSangre = idSangre;
       this.idNacionalidad = idNacionalidad;
    }
   
     @Id 

    
    @Column(name="id_paciente", unique=true, nullable=false)
    public int getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="nombres_paciente", nullable=false, length=40)
    public String getNombresPaciente() {
        return this.nombresPaciente;
    }
    
    public void setNombresPaciente(String nombresPaciente) {
        this.nombresPaciente = nombresPaciente;
    }

    
    @Column(name="apellidos_paciente")
    public String getApellidosPaciente() {
        return this.apellidosPaciente;
    }
    
    public void setApellidosPaciente(String apellidosPaciente) {
        this.apellidosPaciente = apellidosPaciente;
    }

    
    @Column(name="documento_paciente")
    public Integer getDocumentoPaciente() {
        return this.documentoPaciente;
    }
    
    public void setDocumentoPaciente(Integer documentoPaciente) {
        this.documentoPaciente = documentoPaciente;
    }

    
    @Column(name="nacimiento_paciente", nullable=false, length=25)
    public String getNacimientoPaciente() {
        return this.nacimientoPaciente;
    }
    
    public void setNacimientoPaciente(String nacimientoPaciente) {
        this.nacimientoPaciente = nacimientoPaciente;
    }

    
    @Column(name="edad_paciente")
    public Integer getEdadPaciente() {
        return this.edadPaciente;
    }
    
    public void setEdadPaciente(Integer edadPaciente) {
        this.edadPaciente = edadPaciente;
    }

    
    @Column(name="telefono_paciente", length=25)
    public String getTelefonoPaciente() {
        return this.telefonoPaciente;
    }
    
    public void setTelefonoPaciente(String telefonoPaciente) {
        this.telefonoPaciente = telefonoPaciente;
    }

    
    @Column(name="email_paciente", length=30)
    public String getEmailPaciente() {
        return this.emailPaciente;
    }
    
    public void setEmailPaciente(String emailPaciente) {
        this.emailPaciente = emailPaciente;
    }

    
    @Column(name="latitud", length=25)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", length=25)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="id_barrio")
    public Integer getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(Integer idBarrio) {
        this.idBarrio = idBarrio;
    }

    
    @Column(name="id_sexo")
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }

    
    @Column(name="id_sangre")
    public Integer getIdSangre() {
        return this.idSangre;
    }
    
    public void setIdSangre(Integer idSangre) {
        this.idSangre = idSangre;
    }

    
    @Column(name="id_nacionalidad")
    public Integer getIdNacionalidad() {
        return this.idNacionalidad;
    }
    
    public void setIdNacionalidad(Integer idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }




}


