package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paises generated by hbm2java
 */
@Entity
@Table(name="paises"
    ,schema="public"
)
public class Paises  implements java.io.Serializable {


     private int idPais;
     private String nombrePais;

    public Paises() {
    }

    public Paises(int idPais, String nombrePais) {
       this.idPais = idPais;
       this.nombrePais = nombrePais;
    }
   
     @Id 

    
    @Column(name="id_pais", unique=true, nullable=false)
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="nombre_pais", nullable=false, length=30)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }




}


