package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,schema="public"
)
public class Personal  implements java.io.Serializable {


     private int idPersonal;
     private String nombresPersonal;
     private String apellidosPersonal;
     private String documentoPersonal;
     private String direccionPersonal;
     private String nacimientoPersonal;
     private Integer edadPersonal;
     private String emailPersonal;
     private String telefonoPersonal;
     private Integer idCentro;
     private Integer idProfesion;
     private Integer idSexo;
     private Integer idNacionalidad;
     private Integer idTipopersonal;
     private Integer idSangre;
     private Integer idBarrio;

    public Personal() {
    }

	
    public Personal(int idPersonal, String nombresPersonal, String nacimientoPersonal) {
        this.idPersonal = idPersonal;
        this.nombresPersonal = nombresPersonal;
        this.nacimientoPersonal = nacimientoPersonal;
    }
    public Personal(int idPersonal, String nombresPersonal, String apellidosPersonal, String documentoPersonal, String direccionPersonal, String nacimientoPersonal, Integer edadPersonal, String emailPersonal, String telefonoPersonal, Integer idCentro, Integer idProfesion, Integer idSexo, Integer idNacionalidad, Integer idTipopersonal, Integer idSangre, Integer idBarrio) {
       this.idPersonal = idPersonal;
       this.nombresPersonal = nombresPersonal;
       this.apellidosPersonal = apellidosPersonal;
       this.documentoPersonal = documentoPersonal;
       this.direccionPersonal = direccionPersonal;
       this.nacimientoPersonal = nacimientoPersonal;
       this.edadPersonal = edadPersonal;
       this.emailPersonal = emailPersonal;
       this.telefonoPersonal = telefonoPersonal;
       this.idCentro = idCentro;
       this.idProfesion = idProfesion;
       this.idSexo = idSexo;
       this.idNacionalidad = idNacionalidad;
       this.idTipopersonal = idTipopersonal;
       this.idSangre = idSangre;
       this.idBarrio = idBarrio;
    }
   
     @Id 

    
    @Column(name="id_personal", unique=true, nullable=false)
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }

    
    @Column(name="nombres_personal", nullable=false, length=50)
    public String getNombresPersonal() {
        return this.nombresPersonal;
    }
    
    public void setNombresPersonal(String nombresPersonal) {
        this.nombresPersonal = nombresPersonal;
    }

    
    @Column(name="apellidos_personal")
    public String getApellidosPersonal() {
        return this.apellidosPersonal;
    }
    
    public void setApellidosPersonal(String apellidosPersonal) {
        this.apellidosPersonal = apellidosPersonal;
    }

    
    @Column(name="documento_personal")
    public String getDocumentoPersonal() {
        return this.documentoPersonal;
    }
    
    public void setDocumentoPersonal(String documentoPersonal) {
        this.documentoPersonal = documentoPersonal;
    }

    
    @Column(name="direccion_personal", length=50)
    public String getDireccionPersonal() {
        return this.direccionPersonal;
    }
    
    public void setDireccionPersonal(String direccionPersonal) {
        this.direccionPersonal = direccionPersonal;
    }

    
    @Column(name="nacimiento_personal", nullable=false, length=25)
    public String getNacimientoPersonal() {
        return this.nacimientoPersonal;
    }
    
    public void setNacimientoPersonal(String nacimientoPersonal) {
        this.nacimientoPersonal = nacimientoPersonal;
    }

    
    @Column(name="edad_personal")
    public Integer getEdadPersonal() {
        return this.edadPersonal;
    }
    
    public void setEdadPersonal(Integer edadPersonal) {
        this.edadPersonal = edadPersonal;
    }

    
    @Column(name="email_personal", length=30)
    public String getEmailPersonal() {
        return this.emailPersonal;
    }
    
    public void setEmailPersonal(String emailPersonal) {
        this.emailPersonal = emailPersonal;
    }

    
    @Column(name="telefono_personal", length=25)
    public String getTelefonoPersonal() {
        return this.telefonoPersonal;
    }
    
    public void setTelefonoPersonal(String telefonoPersonal) {
        this.telefonoPersonal = telefonoPersonal;
    }

    
    @Column(name="id_centro")
    public Integer getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(Integer idCentro) {
        this.idCentro = idCentro;
    }

    
    @Column(name="id_profesion")
    public Integer getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(Integer idProfesion) {
        this.idProfesion = idProfesion;
    }

    
    @Column(name="id_sexo")
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }

    
    @Column(name="id_nacionalidad")
    public Integer getIdNacionalidad() {
        return this.idNacionalidad;
    }
    
    public void setIdNacionalidad(Integer idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }

    
    @Column(name="id_tipopersonal")
    public Integer getIdTipopersonal() {
        return this.idTipopersonal;
    }
    
    public void setIdTipopersonal(Integer idTipopersonal) {
        this.idTipopersonal = idTipopersonal;
    }

    
    @Column(name="id_sangre")
    public Integer getIdSangre() {
        return this.idSangre;
    }
    
    public void setIdSangre(Integer idSangre) {
        this.idSangre = idSangre;
    }

    
    @Column(name="id_barrio")
    public Integer getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(Integer idBarrio) {
        this.idBarrio = idBarrio;
    }




}


