package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name="receta"
    ,schema="public"
)
public class Receta  implements java.io.Serializable {


     private int idReceta;
     private String tratamiento;
     private Integer idRegistroconsulta;

    public Receta() {
    }

	
    public Receta(int idReceta) {
        this.idReceta = idReceta;
    }
    public Receta(int idReceta, String tratamiento, Integer idRegistroconsulta) {
       this.idReceta = idReceta;
       this.tratamiento = tratamiento;
       this.idRegistroconsulta = idRegistroconsulta;
    }
   
     @Id 

    
    @Column(name="id_receta", unique=true, nullable=false)
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }

    
    @Column(name="tratamiento", length=225)
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }

    
    @Column(name="id_registroconsulta")
    public Integer getIdRegistroconsulta() {
        return this.idRegistroconsulta;
    }
    
    public void setIdRegistroconsulta(Integer idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }




}


