package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegistroConsulta generated by hbm2java
 */
@Entity
@Table(name="registro_consulta"
    ,schema="public"
)
public class RegistroConsulta  implements java.io.Serializable {


     private int idRegistroconsulta;
     private String estado;
     private String cintura;
     private String presion;
     private String estatura;
     private String peso;
     private String horaConsulta;
     private String fechaConsulta;
     private Integer idPaciente;
     private Integer idPersonal;
     private Integer idConsultorio;

    public RegistroConsulta() {
    }

	
    public RegistroConsulta(int idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }
    public RegistroConsulta(int idRegistroconsulta, String estado, String cintura, String presion, String estatura, String peso, String horaConsulta, String fechaConsulta, Integer idPaciente, Integer idPersonal, Integer idConsultorio) {
       this.idRegistroconsulta = idRegistroconsulta;
       this.estado = estado;
       this.cintura = cintura;
       this.presion = presion;
       this.estatura = estatura;
       this.peso = peso;
       this.horaConsulta = horaConsulta;
       this.fechaConsulta = fechaConsulta;
       this.idPaciente = idPaciente;
       this.idPersonal = idPersonal;
       this.idConsultorio = idConsultorio;
    }
   
     @Id 

    
    @Column(name="id_registroconsulta", unique=true, nullable=false)
    public int getIdRegistroconsulta() {
        return this.idRegistroconsulta;
    }
    
    public void setIdRegistroconsulta(int idRegistroconsulta) {
        this.idRegistroconsulta = idRegistroconsulta;
    }

    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cintura", length=25)
    public String getCintura() {
        return this.cintura;
    }
    
    public void setCintura(String cintura) {
        this.cintura = cintura;
    }

    
    @Column(name="presion", length=18)
    public String getPresion() {
        return this.presion;
    }
    
    public void setPresion(String presion) {
        this.presion = presion;
    }

    
    @Column(name="estatura", length=10)
    public String getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(String estatura) {
        this.estatura = estatura;
    }

    
    @Column(name="peso", length=18)
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }

    
    @Column(name="hora_consulta")
    public String getHoraConsulta() {
        return this.horaConsulta;
    }
    
    public void setHoraConsulta(String horaConsulta) {
        this.horaConsulta = horaConsulta;
    }

    
    @Column(name="fecha_consulta", length=18)
    public String getFechaConsulta() {
        return this.fechaConsulta;
    }
    
    public void setFechaConsulta(String fechaConsulta) {
        this.fechaConsulta = fechaConsulta;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="id_personal")
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }

    
    @Column(name="id_consultorio")
    public Integer getIdConsultorio() {
        return this.idConsultorio;
    }
    
    public void setIdConsultorio(Integer idConsultorio) {
        this.idConsultorio = idConsultorio;
    }




}


