package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Seguimiento generated by hbm2java
 */
@Entity
@Table(name="seguimiento"
    ,schema="public"
)
public class Seguimiento  implements java.io.Serializable {


     private int idSeguimiento;
     private String observaciones;
     private String ultimaVisita;
     private String siguienteVisita;
     private Integer idPaciente;

    public Seguimiento() {
    }

	
    public Seguimiento(int idSeguimiento) {
        this.idSeguimiento = idSeguimiento;
    }
    public Seguimiento(int idSeguimiento, String observaciones, String ultimaVisita, String siguienteVisita, Integer idPaciente) {
       this.idSeguimiento = idSeguimiento;
       this.observaciones = observaciones;
       this.ultimaVisita = ultimaVisita;
       this.siguienteVisita = siguienteVisita;
       this.idPaciente = idPaciente;
    }
   
     @Id 

    
    @Column(name="id_seguimiento", unique=true, nullable=false)
    public int getIdSeguimiento() {
        return this.idSeguimiento;
    }
    
    public void setIdSeguimiento(int idSeguimiento) {
        this.idSeguimiento = idSeguimiento;
    }

    
    @Column(name="observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="ultima_visita")
    public String getUltimaVisita() {
        return this.ultimaVisita;
    }
    
    public void setUltimaVisita(String ultimaVisita) {
        this.ultimaVisita = ultimaVisita;
    }

    
    @Column(name="siguiente_visita")
    public String getSiguienteVisita() {
        return this.siguienteVisita;
    }
    
    public void setSiguienteVisita(String siguienteVisita) {
        this.siguienteVisita = siguienteVisita;
    }

    
    @Column(name="id_paciente")
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }




}


