package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoAnalisis generated by hbm2java
 */
@Entity
@Table(name="tipo_analisis"
    ,schema="public"
)
public class TipoAnalisis  implements java.io.Serializable {


     private int idTipoanalisis;
     private String tipoAnalisis;

    public TipoAnalisis() {
    }

	
    public TipoAnalisis(int idTipoanalisis) {
        this.idTipoanalisis = idTipoanalisis;
    }
    public TipoAnalisis(int idTipoanalisis, String tipoAnalisis) {
       this.idTipoanalisis = idTipoanalisis;
       this.tipoAnalisis = tipoAnalisis;
    }
   
     @Id 

    
    @Column(name="id_tipoanalisis", unique=true, nullable=false)
    public int getIdTipoanalisis() {
        return this.idTipoanalisis;
    }
    
    public void setIdTipoanalisis(int idTipoanalisis) {
        this.idTipoanalisis = idTipoanalisis;
    }

    
    @Column(name="tipo_analisis")
    public String getTipoAnalisis() {
        return this.tipoAnalisis;
    }
    
    public void setTipoAnalisis(String tipoAnalisis) {
        this.tipoAnalisis = tipoAnalisis;
    }




}


