package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoPersonal generated by hbm2java
 */
@Entity
@Table(name="tipo_personal"
    ,schema="public"
)
public class TipoPersonal  implements java.io.Serializable {


     private int idTipopersonal;
     private String tipoPersonal;

    public TipoPersonal() {
    }

    public TipoPersonal(int idTipopersonal, String tipoPersonal) {
       this.idTipopersonal = idTipopersonal;
       this.tipoPersonal = tipoPersonal;
    }
   
     @Id 

    
    @Column(name="id_tipopersonal", unique=true, nullable=false)
    public int getIdTipopersonal() {
        return this.idTipopersonal;
    }
    
    public void setIdTipopersonal(int idTipopersonal) {
        this.idTipopersonal = idTipopersonal;
    }

    
    @Column(name="tipo_personal", nullable=false, length=25)
    public String getTipoPersonal() {
        return this.tipoPersonal;
    }
    
    public void setTipoPersonal(String tipoPersonal) {
        this.tipoPersonal = tipoPersonal;
    }




}


