package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoSangre generated by hbm2java
 */
@Entity
@Table(name="tipo_sangre"
    ,schema="public"
)
public class TipoSangre  implements java.io.Serializable {


     private int idSangre;
     private String sangre;

    public TipoSangre() {
    }

    public TipoSangre(int idSangre, String sangre) {
       this.idSangre = idSangre;
       this.sangre = sangre;
    }
   
     @Id 

    
    @Column(name="id_sangre", unique=true, nullable=false)
    public int getIdSangre() {
        return this.idSangre;
    }
    
    public void setIdSangre(int idSangre) {
        this.idSangre = idSangre;
    }

    
    @Column(name="sangre", nullable=false, length=10)
    public String getSangre() {
        return this.sangre;
    }
    
    public void setSangre(String sangre) {
        this.sangre = sangre;
    }




}


