package model;
// Generated 22/10/2015 03:30:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nivel;
     private String usuario;
     private String contrasenha;
     private Integer idPersonal;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String usuario) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
    }
    public Usuario(int idUsuario, String nivel, String usuario, String contrasenha, Integer idPersonal) {
       this.idUsuario = idUsuario;
       this.nivel = nivel;
       this.usuario = usuario;
       this.contrasenha = contrasenha;
       this.idPersonal = idPersonal;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nivel", length=10)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="usuario", nullable=false, length=10)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasenha", length=10)
    public String getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }

    
    @Column(name="id_personal")
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }




}


